[mypy]
ignore_missing_imports = true
plugins = sqlalchemy.ext.mypy.plugin,pydantic.mypy
mypy_path = src
namespace_packages = true
explicit_package_bases = true

show_error_codes = true

# 짜증나는 녀석 1.
disable_error_code = call-overload, annotation-unchecked, union-attr
